dist: trusty
addons:
  postgresql: "9.6"
language: go
services:
  - postgresql
go:
  - "1.12"
before_script:
  - psql -c 'create database marlow_test;' -U postgres
install:
  - go get -v github.com/mattn/go-sqlite3
  - go install -v -x github.com/mattn/go-sqlite3
script:
  - make
  - make test
  - make test-example
  - make example
  - pushd ./examples/library && ./library import ./data/demo-import.json && popd
after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
before_deploy:
  - mkdir -p ./dist/s3-commit/$TRAVIS_COMMIT
  - mkdir -p ./dist/s3-latest/latest
  - cp ./dist/coverage/library.coverage.txt ./dist/s3-commit/$TRAVIS_COMMIT
  - cp ./dist/coverage/library.coverage.html ./dist/s3-commit/$TRAVIS_COMMIT
  - cp ./dist/coverage/library.coverage.txt ./dist/s3-latest/latest
  - cp ./dist/coverage/library.coverage.html ./dist/s3-latest/latest
env:
  global:
  - secure: wJZxvUVrF+CNYQihaZ1ZLloaGN8/7GjZJ7vMUyXQmBwIwMj/bOCxGHBNglX8+o7XqJTVkGSIue0Vk0wic+fy1we8rTtUAfB7RdUyK0EBbOt0GBuziuk03V/cFOW7JodKC/Y3VAiLtOCgpw51KtT2ihg34LjVU3fSRsqIZdg7sskR537rfaZpVlyGVj6ZpD15Tiit4lFbBO9XvjjWi04sS9Q6+z3xMp6kpKfIa5vH1htQOXcsmgwWbT5VcBMsqRW4oDKolt9LbJ1MSrKEmW6/v+mAxCtoyWFPnuqU6/EtQjoTv8S5yu4MAwd6h1N3gS9jvWSW6Vfw8kjzO31fK8ZvMaGqbvERFl9jkHM6WutkklXDEX4YB+vGpxTmP+YjMGXphe2Sw4C9ILBqo49Co7Dz5j16TLK7DX/egpZsKrQcTE1nFZZEzmHHSPSHsn7PXgrcrDNHxtrNsw0sMgAijHRlCBI2w8GMQPIVaw79gpwp1oP21gY6YtIpq0B7SZPcwtTo9N0JxyZ6ZKW0bZIHVqA+R5pB29zvXdjA7JXnKAp4GVOGObxIoclw0csvQmDHxLfd81be0UNB2gTPzBC1CyiGom5lMSqbXIhB7PQF/LcwCP/FUGmnIcXdg3FfMPbdWuYQq9uic1e/s61enJA+cfk7Vxp/ZU2fPH+AKnlliu6wlBw=
  - secure: QB8fkASCOuFVEGzgmaoKI9HmTZebxOEDokevifeUaiK5FkplVwcI9wf0USH/jUYjQ7xFXIl54fNcVgEeC0qVNCggiepnvn3hTquJMM1f8v4dMWXHH3cS9BReMDwmlo43P+Xuw4amcNawMwzYmcqcSODJBJGkWjOM56wiT4Vv2CZE4hPWGyixBfKmenxCb6ncMG7etn81jMP4FNYRnkJnC/g9QBsVxrZN9anhqGNtrOSY4PXEXOcaEwb93rk7hEv0tO83RqIsYNc10jObeV83YyDsxlGIjMsuJnf1Dtp4l7HPtLBavV9GHz5CGG/sHn/R6LV30UNDF9bu4QPHvzf9Vc512tCx+ehlrl7fdpURmdqwDZJJEuKwG7gJ+MOoQitr0wlH/uRYu96AE8Z6MbxhX81mFSg1hh5ZKlsRyuUStT52L7CzKgk311PFZcTfG27ieL7pSRk12hD4jAvihb2O/zdJU27pVPZZMqHTpvmGGwF4y91AWcaOP/LsoD2DTs2H25pLeeryQKPwsp6GKJoKuMeGB1muOW5ecHsQfa9/y6xYPaZoeufS8Wqkk1nJ3fkmDNVCmyv+2Pf5FcWmLZexb8p6FWmDI+EnmCMvKgoarNROxGDHjMbRHoiFUV3ajoDcVGDM4CuIF6NZ0Bj9Xyguet2BixqUOmKO/q31NhqgwHs=
  - secure: sdeCpEcUW5d46RYmbljbTTrp/wxf59YUI602Hup8woZ2Qld4li7x0zd4B1dIGbIq/yXE2qSM/a2JNMOr0+l9tv/hbisBXu3rDQllGWJDTXEAf6QIpEq9qrCd7VsaCJ518rAX7FGaAjoLMpGlJTrW+BZLAy0vXKcKFGrIEA7JCtcWsA8D4hzVeTclbxW9ss+m1yuPI8E5KFdBtXYoKnrlXAZDFiUT3dWuZnteQM0Qdb+MPYlGfs1uMF0zx14ZlKbBNzr0c9e7NG7vX6tmdYj5dH4CP2okV1xUcEluO//cWiiW7m7jYkBlUcr/7Azk6f93U+XyQIrl2yTq72y59XjgPu4GrZ5JX53y7V5CSAoeXBbxPaTCyX3nDQwDaOI1km+vyCD77rxxDX4ig9QsJ2CI0qoIWZb2lBy3tkZaqV7sp+FTIJ5dPSdxbFsSCDa6PKiGS5SY3BYEpPsh3RBVUHApeSd4+H63hjAIms1mNZisFISx5IE1bBHYsF68Hb6M6dVLmgEbxNcwoBffmwzJC2w9f5Qa8Wj6Ru4tg9W30ln/1gd5/LXilLrlrOvd0QYcTUdQiuuSqJzek/UizNFdZxX1pZJPmw8lIa5TnpDWY+CSFxHLjYn/r8c04jks+v/WnI9vVgzpmZXigfAw5RknXkbZ2c045RFmlsmyIUGoWWxwD+s=
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "coverage.marlow.sizethree.cc"
  skip_cleanup: true
  acl: public_read
  local_dir: "./dist/s3-commit"
  on:
    all_branches: true
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "coverage.marlow.sizethree.cc"
  skip_cleanup: true
  acl: public_read
  local_dir: "./dist/s3-latest"
  on:
    branch: master
